#!/usr/bin/env -S node --experimental-strip-types
/**
 * scaffold-mcp.ts — Emit the canonical McpAgent block for a chittyagent-* worker.
 *
 * Implements the SOP defined in docs/MCP-SOP.md §4. This script is the leaf
 * operation that future autobot / autoassist / fractal builders will invoke
 * when bringing a new Bucket C service online.
 *
 * Usage:
 *   ./scripts/scaffold-mcp.ts --service tasks
 *   ./scripts/scaffold-mcp.ts --service finance --workers-root ../chittyentity/workers
 *   ./scripts/scaffold-mcp.ts --service ui --tools list,get,render --dry-run
 *
 * What it does:
 *   1. Reads workers/chittyagent-<name>/{src/index.ts, package.json, wrangler.jsonc}
 *   2. Refuses to overwrite if an McpAgent class is already present
 *   3. Appends the canonical McpAgent block to src/index.ts
 *   4. Adds @modelcontextprotocol/sdk, agents, zod to package.json
 *   5. Adds DO binding + migration entry to wrangler.jsonc
 *   6. Prints the next-step commands (npm install + cf deploy + curl verify)
 *
 * What it does NOT do:
 *   - Implement tool bodies. The scaffold leaves a TODO_TOOL_BODY marker — you
 *     must replace it with a call into the worker's real backend before deploy
 *     (per the "no mocks" rule).
 *   - Touch chittymcp/wrangler.jsonc — that's a separate edit, post-deploy.
 *
 * @canonical-uri chittycanon://core/services/chittymcp#scaffold-mcp
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { parseArgs } from "node:util";

type Args = {
  service: string;
  workersRoot: string;
  tools: string[];
  dryRun: boolean;
};

function parse(): Args {
  const { values } = parseArgs({
    options: {
      service: { type: "string" },
      "workers-root": { type: "string", default: "../chittyentity/workers" },
      tools: { type: "string", default: "list,get" },
      "dry-run": { type: "boolean", default: false },
    },
  });
  if (!values.service) {
    console.error("error: --service <name> is required (e.g. --service finance)");
    process.exit(2);
  }
  return {
    service: values.service,
    workersRoot: values["workers-root"] as string,
    tools: (values.tools as string).split(",").map((s) => s.trim()).filter(Boolean),
    dryRun: !!values["dry-run"],
  };
}

const pascal = (s: string) =>
  s.split(/[-_]/).map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join("");
const upper = (s: string) => s.replace(/-/g, "_").toUpperCase();

function renderToolBlock(service: string, verb: string): string {
  return `  server.tool(
    "${service}_${verb}",
    "TODO: one-line description of ${service}_${verb} (real backend, no mocks)",
    { /* TODO: zod schema */ },
    async (input) => {
      try {
        // TODO_TOOL_BODY: call the worker's real backend function.
        // Replace this throw before committing — per docs/MCP-SOP.md §6.
        throw new Error("${service}_${verb}: not implemented");
      } catch (e) { return _e(\`${service}_${verb} failed: \${(e as Error).message}\`); }
    },
  );`;
}

function renderMcpBlock(service: string, tools: string[]): string {
  const Name = pascal(service);
  const NAME = upper(service);
  const toolBlocks = tools.map((v) => renderToolBlock(service, v)).join("\n\n");
  return `
// ── MCP Server ──────────────────────────────────────────────────────
// Generated by scripts/scaffold-mcp.ts. Replace TODO_TOOL_BODY markers with
// real backend calls before deploy. See docs/MCP-SOP.md §4 + §6.

import { McpAgent } from "agents/mcp";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

const ${NAME}_VERSION = "0.1.0";
const _t = (d: unknown) => ({ content: [{ type: "text" as const, text: typeof d === "string" ? d : JSON.stringify(d, null, 2) }] });
const _e = (m: string) => ({ content: [{ type: "text" as const, text: m }], isError: true as const });

function register${Name}Tools(server: McpServer, env: Env) {
${toolBlocks}
}

export class ${Name}Agent extends McpAgent<Env> {
  server = new McpServer({ name: "chittyagent-${service}", version: ${NAME}_VERSION });
  async init() { register${Name}Tools(this.server, this.env); }
}

const ${service.replace(/-/g, "_")}McpHandler = ${Name}Agent.serve("/mcp", { binding: "${NAME}_AGENT" });
`;
}

function updatePackageJson(pkgPath: string, dryRun: boolean): void {
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
  pkg.dependencies ??= {};
  let changed = false;
  for (const [dep, ver] of [
    ["@modelcontextprotocol/sdk", "^1.25.2"],
    ["agents", "^0.3.10"],
    ["zod", "^3.23.0"],
  ] as const) {
    if (!pkg.dependencies[dep]) {
      pkg.dependencies[dep] = ver;
      changed = true;
    }
  }
  if (!changed) {
    console.log(`  package.json: deps already present, no change`);
    return;
  }
  if (dryRun) {
    console.log(`  [dry-run] package.json: would add 3 deps`);
    return;
  }
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
  console.log(`  package.json: added MCP deps`);
}

function updateWrangler(wranglerPath: string, service: string, dryRun: boolean): void {
  const Name = pascal(service);
  const NAME = upper(service);
  const raw = readFileSync(wranglerPath, "utf8");
  if (raw.includes(`"${NAME}_AGENT"`) || raw.includes(`${Name}Agent`)) {
    console.log(`  wrangler.jsonc: DO binding already present, no change`);
    return;
  }
  console.log(`  wrangler.jsonc: needs manual addition of:`);
  console.log(`    durable_objects.bindings[] += { "name": "${NAME}_AGENT", "class_name": "${Name}Agent" }`);
  console.log(`    migrations[] += { "tag": "<next>", "new_sqlite_classes": ["${Name}Agent"] }`);
  if (!dryRun) {
    // Conservative: don't auto-edit JSONC (comments are not preserved by JSON.parse).
    // Print instructions and exit; humans/PR review apply the edit.
  }
}

function appendMcpBlock(indexPath: string, service: string, tools: string[], dryRun: boolean): void {
  const src = readFileSync(indexPath, "utf8");
  if (src.includes("McpAgent") || src.includes("McpServer")) {
    throw new Error(`${indexPath}: McpAgent/McpServer already present — refusing to overwrite`);
  }
  const block = renderMcpBlock(service, tools);
  const insertion = `\n${block}\n`;
  if (dryRun) {
    console.log(`  [dry-run] src/index.ts: would append ${insertion.split("\n").length} lines`);
    return;
  }
  writeFileSync(indexPath, src + insertion);
  console.log(`  src/index.ts: appended McpAgent block (${tools.length} tools, TODO bodies)`);
}

function main() {
  const args = parse();
  const workerDir = resolve(args.workersRoot, `chittyagent-${args.service}`);
  if (!existsSync(workerDir)) {
    console.error(`error: worker dir not found: ${workerDir}`);
    process.exit(1);
  }
  const indexPath = join(workerDir, "src/index.ts");
  const pkgPath = join(workerDir, "package.json");
  const wranglerPath = existsSync(join(workerDir, "wrangler.jsonc"))
    ? join(workerDir, "wrangler.jsonc")
    : join(workerDir, "wrangler.toml");

  console.log(`Scaffolding MCP layer for chittyagent-${args.service}`);
  console.log(`  worker dir: ${workerDir}`);
  console.log(`  tools: ${args.tools.join(", ")}`);
  console.log(`  dry-run: ${args.dryRun}`);
  console.log("");

  appendMcpBlock(indexPath, args.service, args.tools, args.dryRun);
  updatePackageJson(pkgPath, args.dryRun);
  updateWrangler(wranglerPath, args.service, args.dryRun);

  console.log("");
  console.log("Next steps:");
  console.log(`  1. Edit src/index.ts and replace TODO_TOOL_BODY markers with real backend calls`);
  console.log(`  2. Apply the wrangler.jsonc edits printed above`);
  console.log(`  3. Wire ${args.service.replace(/-/g, "_")}McpHandler into the default export's fetch path`);
  console.log(`  4. cd ${workerDir} && npm install && npx cf deploy --env production`);
  console.log(`  5. Verify: curl -sX POST https://${args.service}.chitty.cc/mcp \\`);
  console.log(`       -H 'content-type: application/json' \\`);
  console.log(`       -H 'accept: application/json, text/event-stream' \\`);
  console.log(`       -d '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-03-26","capabilities":{},"clientInfo":{"name":"v","version":"1"}}}'`);
  console.log(`     Then re-send method=tools/list with the returned Mcp-Session-Id header.`);
  console.log(`  6. Add SVC_${upper(args.service)} binding to chittymcp/wrangler.jsonc + SERVICE_MAP.`);
}

main();
